# Generated by Django 6.0 on 2025-12-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('quiz', 'Quiz'), ('tarea', 'Tarea')], max_length=20)),
                ('contenido', models.TextField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('orden', models.IntegerField()),
                ('recursos', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo')),
            ],
            options={
                'db_table': 'leccion',
                'ordering': ['orden'],
            },
        ),
    ]
